### ISSUE TITLE
[BUG] Responsividade

### ISSUE THREAD

**Issue by Frotas** [Squad-61/Web_Site#13]
**Descreva o Erro/Problema/Bug**
A responsividade das paginas [Home](https://squad-61.github.io/Web_Site/), [Feed](https://squad-61.github.io/Web_Site/public/pages/feed), [Leitura Assistida](https://squad-61.github.io/Web_Site/public/pages/games/leitura_assistida) e [Sobre](https://squad-61.github.io/web_site/public/pages/about) estão fora de escala em dispositivos menores (Smartphone e Tablet). 

**Comportamento esperado**
Os components deveriam se adaptar ao tamanho do aparelho.

**Screenshots**
<div align="center">
  <img src="https://user-images.githubusercontent.com/89676387/180667583-389d640a-a527-4277-b785-9416103dd51b.png" alt="homePage_bug_report" height="600px" width="360px"/>
</div>

**Smartphone (Por favor, complete a seguinte informação):**
 - Device: Sansung J410G
 - OS: Android 8.1.0
 - Browser: Google Chrome
 - Version: 103.0.5060.129

**Comment by Frotas** [comment]
Andamento da correção da responsividade das paginas:
- [ ] Home Page
- [ ] About Page
- [ ] Watched Learning Page

**Comment by Frotas** [comment]
# Relatório
As paginas estão responsivas de acordo com o padrão de estilização do _Mobile First_ , além da responsividade corrigida, fiz um sistema de palheta de cores através de variáveis CSS, troquei as cores para tons pasteis, para deixar mais atrativo ao publico alvo. Fiz remoções de TAG HTML que não são mais utilizadas.
Agora só resta realizar as adaptações para Desktop.

**Comment by Guimillen** [comment]
Utilizando o website pelo meu telefone, não encontrei problema no enquadramento da tela.

Modelo: moto x4
OS : android 9
Browser: Google Chrome.
